spring:
  datasource:
    username: root
    password: 7897506
    url: jdbc:mysql://192.168.159.128:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
#    filters: stat
#    filters: stat
#    proxy-filters: [stat]
#    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    #打印SQL
    show-sql: true
    #是jpa层面对数据表生成策略的控制
    generate-ddl: true
    hibernate:
      #是jpa实现hibernate层面上对数据表生成策略的控制
      #指定命名策略
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true



mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml #指定主配置文件
  mapper-locations: classpath:/mybatis/mapper/*.xml # 指定xml映射文件路径
  type-aliases-package: com.shlock.springboot_mybatis.domain # 指定mybatis别名包
logging:
  level:
    com.shlock.springboot_mybatis.dao: debug # 配置日志
